version: '3.8'
services:
  postgres:
    container_name: postgres
    build: ../.
    tty: true
    stdin_open: true
    # command: /bin/bash # to stop the container from starting supervisord
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: user
      POSTGRES_DATABASE: test-db
      POSTGRES_PASSWORD: secret
      DUMP_STRATEGY: minimal
      DUMP_TIME: '* * * * *'
      BASEBACKUP_TIME: '*/5 * * * *'
    volumes:
      - '${PWD}/docker/postgres:/postgres'
      - '${PWD}/docker/backup:/backup'
    ports:
      - 5432:5422 # postgres
    networks:
      - default
